// SPDX-License-Identifier: MIT

#ifndef OQS_SIG_RACCOONG_PARAMS_H
#define OQS_SIG_RACCOONG_PARAMS_H

#include <stddef.h>
#include <stdint.h>

#define RACCOONG_44_PUBLIC_KEY_BYTES 16144
#define RACCOONG_44_SECRET_KEY_BYTES 32272
#define RACCOONG_44_SIGNATURE_BYTES 20768
#define RACCOONG_44_SEED_BYTES 32
#define RACCOONG_44_CHAINCODE_BYTES 32
#define RACCOONG_44_RERAND_BYTES 64

#endif // OQS_SIG_RACCOONG_PARAMS_H
